#!/bin/bash


ACTION="$1"

case $ACTION in

	remove)

		apt-get remove -y acroread-bin
		TEST=$( dpkg-query -s  acroread-bin 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi
	;;	
esac
exit 0